basic/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\SignupForm;
use app\models\AdminPanelForm;
use app\models\AddMovieForm;
use app\models\AddActorForm;
use app\models\IndexForm;
use yii\data\ActiveDataProvider;
use app\models\Movie;
use app\models\Actor;
use app\models\MovieForm;
use app\models\ActorForm;
use app\models\EditActorForm;

class SiteController extends Controller {
    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [ 
                'access' => [ 
                        'class' => AccessControl::className (),
                        'only' => [ 
                                'logout',
                                'signup' 
                        ],
                        'rules' => [ 
                                [ 
                                        'actions' => [ 
                                                'signup' 
                                        ],
                                        'allow' => true,
                                        'roles' => [ 
                                                '?' 
                                        ] 
                                ],
                                [ 
                                        'actions' => [ 
                                                'logout' 
                                        ],
                                        'allow' => true,
                                        'roles' => [ 
                                                '@' 
                                        ] 
                                ] 
                        ] 
                ],
                'verbs' => [ 
                        'class' => VerbFilter::className (),
                        'actions' => [ 
                                'logout' => [ 
                                        'post' 
                                ] 
                        ] 
                ] 
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function actions() {
        return [ 
                'error' => [ 
                        'class' => 'yii\web\ErrorAction' 
                ],
                'captcha' => [ 
                        'class' => 'yii\captcha\CaptchaAction',
                        'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null 
                ] 
        ];
    }
    
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        $model = new IndexForm ();
        
        if ($model->load ( Yii::$app->request->post () )) {
            return $this->redirect ( $model->search () );
        }
        
        return $this->render ( 'index', [ 
                'model' => $model 
        ] );
    }
    
    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (! Yii::$app->user->isGuest) {
            return $this->goHome ();
        }
        
        $model = new LoginForm ();
        if ($model->load ( Yii::$app->request->post () ) && $model->login ()) {
            return $this->goBack ();
        }
        return $this->render ( 'login', [ 
                'model' => $model 
        ] );
    }
    
    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout ();
        
        return $this->goHome ();
    }
    
    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact() {
        $model = new ContactForm ();
        if ($model->load ( Yii::$app->request->post () ) && $model->contact ( Yii::$app->params ['adminEmail'] )) {
            Yii::$app->session->setFlash ( 'contactFormSubmitted' );
            
            return $this->refresh ();
        }
        return $this->render ( 'contact', [ 
                'model' => $model 
        ] );
    }
    
    /**
     * Singup action.
     *
     * @return string
     */
    public function actionSignup() {
        $model = new SignupForm ();
        if ($model->load ( Yii::$app->request->post () )) {
            if ($user = $model->signup ()) {
                if (Yii::$app->getUser ()->login ( $user )) {
                    return $this->goHome ();
                }
            }
        }
        
        return $this->render ( 'signup', [ 
                'model' => $model 
        ] );
    }
    
    /**
     * Adminpanel action
     */
    public function actionAdminpanel() {
        $model = new AdminPanelForm ();
        
        if ($model->load ( Yii::$app->request->post () )) {
            $model->accept ();
            $this->refresh ();
        }
        
        return $this->render ( 'adminpanel', [ 
                'model' => $model 
        ] );
    }
    
    /**
     * Add movie action
     */
    public function actionAddmovie() {
        $model = new AddMovieForm ();
        
        if ($model->load ( Yii::$app->request->post () ) && $movie = $model->addMovie ()) {
            $this->refresh ();
        }
        
        return $this->render ( 'addmovie', [ 
                'model' => $model 
        ] );
    }
    
    /**
     * Add actor action
     */
    public function actionAddactor() {
        $model = new AddActorForm ();
        
        if ($model->load ( Yii::$app->request->post () ) && $actor = $model->addactor ()) {
            $this->refresh ();
        }
        
        return $this->render ( 'addactor', [ 
                'model' => $model 
        ] );
    }
    
    /**
     *
     * @return string
     */
    public function actionMovies() {
        $ids = Yii::$app->request->get ( 'ids' );
        
        if (empty ( $ids )) {
            $dataprovider = new ActiveDataProvider ( [ 
                    'query' => Movie::find ()->where(['status' => Movie::STATUS_ACTIVE]),
                    'pagination' => [ 
                            'pageSize' => 20 
                    ] 
            ] );
        } else {
            $dataprovider = new ActiveDataProvider ( [ 
                    'query' => Movie::find ()->filterWhere ( [ 
                            'in',
                            'id',
                            $ids 
                    ] ),
                    'pagination' => [ 
                            'pageSize' => 20 
                    ] 
            ] );
        }
        
        return $this->render ( 'movies', [ 
                'dataProvider' => $dataprovider 
        ] );
    }
    
    /**
     *
     * @return string
     */
    public function actionActors() {
        $ids = Yii::$app->request->get ( 'ids' );
        if (empty ( $ids )) {
            $dataprovider = new ActiveDataProvider ( [ 
                    'query' => Actor::find (),
                    'pagination' => [ 
                            'pageSize' => 20 
                    ] 
            ] );
        } else {
            $dataprovider = new ActiveDataProvider ( [ 
                    'query' => Actor::find ()->filterWhere ( [ 
                            'in',
                            'id',
                            $ids 
                    ] ),
                    'pagination' => [ 
                            'pageSize' => 20 
                    ] 
            ] );
        }
        
        return $this->render ( 'actors', [ 
                'dataProvider' => $dataprovider 
        ] );
    }
    
    /**
     *
     * @return string
     */
    public function actionMovie() {
        $model = new MovieForm ();
        if( $model->load ( Yii::$app->request->post () )){
	        if (isset ( $_POST ['delete-button'] )) {
	            if ($movie_to_remove = $model->remove ()) {
	                \Yii::$app->session->setFlash ( 'success', 'Twoje zgłoszenie zostało wysłane.' );
	            }
	        } else if (isset ( $_POST ['edit-button'] )) {
	            \Yii::trace ( 'edit button clicked' );
	            /*
	             * return $this->redirect ( [
	             * 'editactor',
	             * 'id' => $model->actor->id
	             * ] );
	             */
	        } else if (isset ( $_POST ['rate-button'] ) ) {
	            if ($makr = $model->addMark ()) {
	                \Yii::$app->session->setFlash ( 'success', 'Ocena została dodana.' );
	            }
	        } else if (isset ( $_POST ['comment-button'] )) {
	            if ($comment = $model->addComment ()) {
	                $this->refresh ();
	            }
	        }   
        }
        
        return $this->render ( 'movie', [ 
                'model' => $model 
        ] );
    }
    
    /**
     *
     * @return string
     */
    public function actionActor() {
        $model = new ActorForm ();
        $model->actor = Actor::findById ( Yii::$app->request->get ( 'id' ) );
        
        if (isset ( $_POST ['delete-button'] )) {
            if($model->remove()){
                \Yii::$app->session->setFlash ( 'success', 'Twoje zgłoszenie zostało wysłane' );
            }
        } else if (isset ( $_POST ['edit-button'] )) {
            return $this->redirect ( [ 
                    'editactor',
                    'id' => $model->actor->id 
            ] );
        }
        return $this->render ( 'actor', [ 
                'model' => $model 
        ] );
    }
    
    /**
     *
     * @return string
     */
    public function actionEditactor() {
        $model = new EditActorForm ();
        
        if ($model->load ( Yii::$app->request->post () ) && $editActor = $model->editActor ()) {
            \Yii::$app->session->setFlash ( 'success', 'Twoje zgłoszenie zostało wysłane' );
            return $this->redirect ( [ 
                    'actor',
                    'id' => $model->id 
            ] );
        }
        

basic/views/site/_movie.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;
use app\models\Country;
use app\models\MovieCountry;
use app\models\MovieGenre;
use app\models\Genre;
use app\models\Mark;
?>
<style>
.movie
{
    text-align: left;
    margin-bottom: 20px;
}

.box1{
    width:auto;
    height:auto;
    display:inline-block;
    margin-right: 20px;
}
.box2{
    height:auto;
    display:inline-block;
}

</style>

<div class="movie">
		<div class="box1">
			<?= Html::img($model->poster, ['width' => '122', 'height' => '182'])?>
		</div>
		<div class="box2">
		    <?= Html::a(Html::encode($model->title), Url::to(['site/movie', 'id' => $model->id])) ?> <br>
	    	<?= HtmlPurifier::process($model->description) ?>  <br>
	    	<?php
	    		echo 'Kraj produkcji: ';
	    		foreach(MovieCountry::findByMovieId($model->id) as $movieCountry){
	    			$country = Country::findById($movieCountry->country_id);
	    			echo $country->name;
	    		}
	    		echo '<br>';
	    		echo 'Rodzaj filmu: ';
	    		foreach(MovieGenre::findByMovieId($model->id) as $movieGenre){
	    			$genre = Genre::findById($movieGenre->genre_id);
	    			echo $genre->name;
					echo ' ';
	    		}
	    		$mark = Mark::find()->select(['AVG(mark) as mark'])->where(['movie_id' => $model->id])->one();
	    		//Yii::trace($mark->mark);
	    		echo '<br>Ocena: ';
	    		if($mark->mark == null){
	    		    echo 'Brak ocen.';
	    		}else{
	    		    echo $mark->mark.' / 10';
	    		}
	    	?>
		</div>
</div>

basic/views/site/_post.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
?>
<div class="post">
    <h2><?= Html::encode($model->title) ?></h2>
	<?= Html::img($model->poster)?>
    <?= HtmlPurifier::process($model->description) ?>  
    <?= Html::label($model->budget) ?>  
</div>

basic/views/site/actor.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use app\models\Role;
use app\models\Movie;
use app\models\Director;
use app\models\ActorToRemove;

$this->title = $model->actor->name;
$this->params ['breadcrumbs'] [] = $this->title;
?>
<style>
td{
	padding-right: 20px;
	padding-left: 20px;
	width: 250px;
}
.parent
{
    text-align: left;
    margin-bottom: 20px;
    overflow:auto; 
}

.box1{
    float:left;
    margin-right: 20px;
}

.box2{
    display: table-cell;
    float:right; 
}

button{
	width: 100%;
}
</style>
<div class="site-actor">
	<div class="parent">
		<div class="box1">
			<h1><?= Html::encode($this->title) ?></h1>
		    Data urodzenia: <?= $model->actor->date_of_birth ?> <br>
		    Data śmierci: 
		    <?php if($model->actor->date_of_death !== null){
		    	echo $model->actor->date_of_death;
		    }else{
		    	echo '-';
		    }?>
    	</div>
    	<div class="box2">
   			<?php $form = ActiveForm::begin(['id' => 'actor-form']); ?>
   			<div class="form-group">
			    <?php
			         $to_remove = ActorToRemove::findByActorId($model->actor->id);
			         if(empty($to_remove)){
			             echo Html::submitButton('Usuń', ['class' => 'btn btn-primary', 'name' => 'delete-button']).'<br>';
			         }
			         echo Html::submitButton('Edytuj', ['class' => 'btn btn-primary', 'name' => 'edit-button']);
			    ?>
			</div>
			<?php ActiveForm::end(); ?>
		</div>
	</div>
	<h3>Filmografia:</h3>
	<h4>Reżyser:</h4>
	<?php 
		foreach(Director::findByActoreId($model->actor->id) as $director){
			$movie = Movie::findById($director->movie_id);
			echo Html::a(Html::encode($movie->title), Url::to(['site/movie', 'id' => $movie->id])).'<br>';
		}
	?>
	
	<h4>Aktor:</h4>
	<?php 
		echo '<table>';
		foreach(Role::findByActoreId($model->actor->id) as $director){
			$movie = Movie::findById($director->movie_id);
			echo '<tr><td>'.Html::a(Html::encode($movie->title), Url::to(['site/movie', 'id' => $movie->id])).'</td><td>'.$director->name.'</td></tr>';

		}
		echo '</table>';
	?>

</div>

basic/views/site/actors.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
use yii\helpers\Html;
use yii\widgets\ListView;
use yii\base\Widget;

$this->title = 'Aktorzy i reżyserzy';
$this->params ['breadcrumbs'] [] = $this->title;
?>
<div class="site-actors">
	<h1><?= Html::encode($this->title) ?></h1>
	<?=ListView::widget ( [ 
			'dataProvider' => $dataProvider,
			'itemView' => '_actor',
			'pager' => [
					'firstPageLabel' => 'first',
					'lastPageLabel' => 'last',
					'prevPageLabel' => 'previous',
					'nextPageLabel' => 'next',
					'maxButtonCount' => 3,
				]
	] )?>
</div>

basic/views/site/addactor.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\AddActorForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Dodaj aktora/reżysera';
$this->params ['breadcrumbs'] [] = $this->title;
?>
<div class="site-addactor">
	<h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(['id' => 'addactor-form']); ?>

        <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

        <?=$form->field ( $model, 'date_of_birth' )->widget ( \yii\widgets\MaskedInput::className (), [ 'mask' => '9999-99-99' ] )?>

         <?=$form->field ( $model, 'date_of_death' )->widget ( \yii\widgets\MaskedInput::className (), [ 'mask' => '9999-99-99' ] )?>
        
        <div class="form-group">
        	<?= Html::submitButton('Dodaj', ['class' => 'btn btn-primary', 'name' => 'addactor-button']) ?>
        </div>
        
    <?php ActiveForm::end(); ?>
    <p>work in progess.</p>
</div>

basic/views/site/addmovie.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\AddMovieForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Dodaj film';
$this->params ['breadcrumbs'] [] = $this->title;
?>
<div class="site-addmovie">
	<h1><?= Html::encode($this->title) ?></h1>

           	<?php $form = ActiveForm::begin(['id' => 'addmovie-form']); ?>

			<?= $form->field($model, 'title')->textInput(['autofocus' => true]) ?>
			
			<?= $form->field($model, 'directors')->textarea()?>
			
			<?= $form->field($model, 'actors')->textarea()?>
			
			<?= $form->field($model, 'genres')->textInput() ?>
			
			<?= $form->field($model, 'countries')->textInput() ?>
			
			<?= $form->field($model, 'budget')->textInput() ?>
			
			<?= $form->field($model, 'year')->textInput() ?>

			<?= $form->field($model, 'poster')->textInput() ?>
			
			<?= $form->field($model, 'description')->textarea()?>
			
			<div class="form-group">
        		<?= Html::submitButton('Dodaj', ['class' => 'btn btn-primary', 'name' => 'addmovie-button']) ?>
        	</div>

           	<?php ActiveForm::end(); ?>

    <p>work in progess.</p>
</div>

basic/views/site/adminpanel.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\AdminPanelForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Panel administracyjny';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-adminpanel">
    <h1><?= Html::encode($this->title) ?></h1>
	<div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['id' => 'adminpanel-form']); ?>

                <?= $form->field($model, 'reportType')->dropDownList($model->getReportTypes(), ['autofocus' => true, 'onchange' => '']); ?>
                
                <?= $form->field($model, 'reports')->listBox($model->getReport(), ['multiple' => true]); ?>
                
             	<div class="form-group">
            		<?= Html::submitButton('Zaakceptuj', ['class' => 'btn btn-primary', 'name' => 'accept-button']) ?>
    			</div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

basic/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params ['breadcrumbs'] [] = $this->title;
?>
<div class="site-contact">
	<h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">Thank you for contacting us. We
		will respond to you as soon as possible.</div>

	<p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>
		. Please configure the
		<code>useFileTransport</code>
		property of the
		<code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>If you have business inquiries or other questions, please
		fill out the following form to contact us. Thank you.</p>

	<div class="row">
		<div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?=$form->field ( $model, 'verifyCode' )->widget ( Captcha::className (), [ 'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>' ] )?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
	</div>

    <?php endif; ?>
</div>

basic/views/site/editactor.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = $model->name;
$this->params ['breadcrumbs'] [] = $this->title;
?>
<div class="site-editactor">
	<h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(['id' => 'editactor-form']); ?>

        <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

        <?=$form->field ( $model, 'date_of_birth' )->widget ( \yii\widgets\MaskedInput::className (), [ 'mask' => '9999-99-99' ] )?>

         <?=$form->field ( $model, 'date_of_death' )->widget ( \yii\widgets\MaskedInput::className (), [ 'mask' => '9999-99-99' ] )?>
        
        <div class="form-group">
        	<?= Html::submitButton('Zgłoś zmiany', ['class' => 'btn btn-primary', 'name' => 'editactor-button']) ?>
        </div>
        
    <?php ActiveForm::end(); ?>
    <p>work in progess.</p>
</div>

basic/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

basic/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

basic/views/site/movie.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use app\models\MovieCountry;
use app\models\Country;
use app\models\MovieGenre;
use app\models\Genre;
use app\models\Director;
use app\models\Actor;
use app\models\Role;
use app\models\User;
use app\models\Comment;
use app\models\Mark;
use app\models\MovieToRemove;

$this->title = $model->movie->title;
$this->params ['breadcrumbs'] [] = $this->title;
?>
<style>
td{
	padding-right: 20px;
	padding-left: 20px;
	width: 250px;
}
.parent
{
    text-align: left;
    margin-bottom: 20px;
    overflow:auto; 
}

.box1{
    float:left;
    margin-right: 20px;
}

.box2{
    float:left;
    margin-right: 20px;
}
.box3{
    display: table-cell;
    float:right;
}
button{
    width: 100%
}
</style>
<div class="site-movie">
	<div class="parent">
		<div class="box1">
			<?= Html::img($model->movie->poster, ['width' => '183', 'height' => '273'])?>
		</div>
		<div class="box2">
		<h1><?= Html::encode($this->title) ?></h1>
		<?= HtmlPurifier::process($model->movie->description) ?>  <br>
		<?php
		echo 'W reĹĽyserii: ';
		foreach (Director::findByMovieId($model->movie->id) as $director ){
			$actor = Actor::findById($director->actor_id);
			echo Html::a(Html::encode($actor->name), Url::to(['site/actor', 'id' => $actor->id]));
			echo ', ';
		}
	 	
		echo '<br> Kraj produkcji: ';
		foreach ( MovieCountry::findByMovieId ( $model->movie->id ) as $movieCountry ) {
			$country = Country::findById ( $movieCountry->country_id );
			echo $country->name;
			echo ', ';
		}
		echo '<br>';
		echo 'Rodzaj filmu: ';
		foreach ( MovieGenre::findByMovieId ( $model->movie->id ) as $movieGenre ) {
			$genre = Genre::findById ( $movieGenre->genre_id );
			echo $genre->name;
			echo ', ';
		}
		echo '<br> Rok produkcji ';
		echo $model->movie->year;
		$user = User::findIdentityWithoutStatus($model->movie->user_id);
		echo '<br> Dodane przez: ';
		echo $user->username;
		?> <br>
		BudĹĽet: <?=$model->movie->budget ?> mln <br>
		Ocena: 
		<?php 
		  $mark = Mark::find()->select(['AVG(mark) as mark'])->where(['movie_id' => $model->movie->id])->one();
    		if($mark->mark == null){
    		    echo 'Brak ocen.';
    		}else{
    		    echo $mark->mark.' / 10';
    		}
		?>
		</div>
		<div class="box3">
			<?php $form = ActiveForm::begin(['id' => 'action-form']);
			     $rate = Mark::findByMovieIdAndUserId($model->movie->id, Yii::$app->user->id);
			     if(empty($rate)){
    		         echo $form->field($model, 'rate')->dropDownList($model->rates());
    				 echo Html::submitButton('Oceń', ['class' => 'btn btn-primary', 'name' => 'rate-button']).'<br>';
			     }
			     $to_remove = MovieToRemove::findByMovieId($model->movie->id);
			     if(empty($to_remove)){
			         echo Html::submitButton('Usuń', ['class' => 'btn btn-primary', 'name' => 'delete-button']).'<br>';
			     }
			     echo Html::submitButton('Edytuj', ['class' => 'btn btn-primary', 'name' => 'edit-button']);
			     ActiveForm::end();
	       ?>
		</div>
	</div>
	<h3>Obsada:</h3>
	<?php 
		echo '<table>';
		foreach(Role::findByMovieId($model->movie->id) as $role){
			$actor = Actor::findById($role->actor_id);
			echo '<tr><td>'.Html::a(Html::encode($actor->name), Url::to(['site/actor', 'id' => $actor->id])).'</td><td>'.$role->name.'</td></tr>';

		}
		echo '</table>';
	?>
	
	<h2>Komentarze:</h2>
	<?php 
	if(!Yii::$app->user->isGuest){
	    $array = Comment::findByMovieAdnUserId($model->movie->id, Yii::$app->user->id);
	    if(empty( $array ))
	    {
        	$form = ActiveForm::begin(['id' => 'movie-form']);
            echo $form->field($model, 'comment')->textarea(['rows' => 6]);
            echo Html::submitButton('Dodaj', ['class' => 'btn btn-primary', 'name' => 'comment-button']);
        	ActiveForm::end();
	    }
	}
	
    foreach(Comment::findByMovieId($model->movie->id) as $comment){
        $user = User::findIdentity($comment->user_id);
        echo $comment->date.' '.$user->username.'<br>'.$comment->text.'<br>';
    }
    ?>

</div>